"""Pydantic models for case reviews and annotations."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field

Severity = Literal["note", "issue", "error"]
ReviewStatus = Literal["pending", "in_progress", "needs_changes", "approved"]


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class FieldAnnotation(BaseModel):
    """A comment attached to a specific field of a case."""

    id: str = Field(..., description="UUID, generated by client for optimistic UI")
    field_path: str = Field(..., min_length=1, max_length=512)
    field_snippet: str | None = Field(
        default=None,
        max_length=400,
        description="Excerpt of the field value at annotation time (orphan recovery)",
    )
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
    resolved: bool = False


class CaseComment(BaseModel):
    """A free-text comment attached to the whole case (case-wide thread)."""

    id: str
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)


class CaseReview(BaseModel):
    """Single reviewer's review state for a single case."""

    case_id: str
    dataset_version: str
    reviewer_code: str
    status: ReviewStatus = "pending"
    field_annotations: list[FieldAnnotation] = Field(
        default_factory=list, max_length=2000
    )
    case_comments: list[CaseComment] = Field(default_factory=list, max_length=500)
    first_opened_at: datetime | None = None
    last_updated_at: datetime = Field(default_factory=_utcnow)
    # Stamped on every heartbeat (which only fires when the tab is visible AND the
    # user actually interacted within the last minute). Lets the admin progress
    # view distinguish in-progress-now from in-progress-but-stale.
    last_active_at: datetime | None = None
    time_spent_seconds: int = 0


# --- Request payloads --------------------------------------------------

class FieldAnnotationCreate(BaseModel):
    id: str
    field_path: str = Field(..., min_length=1, max_length=512)
    field_snippet: str | None = Field(default=None, max_length=400)
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"


class FieldAnnotationUpdate(BaseModel):
    comment: str | None = Field(default=None, min_length=1, max_length=4000)
    severity: Severity | None = None
    field_snippet: str | None = Field(default=None, max_length=400)
    resolved: bool | None = None


class CaseCommentCreate(BaseModel):
    id: str
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"


class CaseCommentUpdate(BaseModel):
    comment: str | None = Field(default=None, min_length=1, max_length=4000)
    severity: Severity | None = None


class StatusUpdate(BaseModel):
    status: ReviewStatus


class HeartbeatRequest(BaseModel):
    seconds: int = Field(..., ge=1, le=600)


# --- Lightweight summary used by the case list ------------------------

class CaseReviewSummary(BaseModel):
    """One entry in the my-reviews list — cheap to compute, easy to render."""

    case_id: str
    status: ReviewStatus
    annotation_count: int
    comment_count: int
    severity_counts: dict[str, int]   # {"note": N, "issue": N, "error": N}
    last_updated_at: datetime | None
