"""Pydantic models for clinician policy review and field annotations."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field


Severity = Literal["note", "issue", "error"]
ReviewStatus = Literal["pending", "in_progress", "needs_changes", "approved"]
DimensionDecision = Literal["approve", "needs_revision"]


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class PolicyReviewVerdict(BaseModel):
    """A physician's explicit judgment of every benchmark policy dimension."""

    scenario_plausibility: DimensionDecision
    diagnosis: DimensionDecision
    actions: DimensionDecision
    avoided_actions: DimensionDecision
    sequencing: DimensionDecision
    stopping: DimensionDecision
    assessment: DimensionDecision
    comment: str = Field(default="", max_length=4000)
    submitted_at: datetime = Field(default_factory=_utcnow)

    @property
    def approves_all(self) -> bool:
        return all(
            value == "approve"
            for name, value in self.model_dump().items()
            if name not in {"comment", "submitted_at"}
        )


class FieldAnnotation(BaseModel):
    id: str = Field(..., description="UUID, generated by client for optimistic UI")
    field_path: str = Field(..., min_length=1, max_length=512)
    field_snippet: str | None = Field(default=None, max_length=400)
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
    resolved: bool = False


class CaseComment(BaseModel):
    id: str
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)


class CaseReview(BaseModel):
    """One independent clinician's review of one case and its scoring policy."""

    case_id: str
    dataset_version: str
    reviewer_code: str
    status: ReviewStatus = "pending"
    policy_verdict: PolicyReviewVerdict | None = None
    field_annotations: list[FieldAnnotation] = Field(default_factory=list, max_length=2000)
    case_comments: list[CaseComment] = Field(default_factory=list, max_length=500)
    first_opened_at: datetime | None = None
    last_updated_at: datetime = Field(default_factory=_utcnow)
    last_active_at: datetime | None = None
    time_spent_seconds: int = 0

    @property
    def unresolved_errors(self) -> int:
        return sum(
            annotation.severity == "error" and not annotation.resolved
            for annotation in self.field_annotations
        )


class FieldAnnotationCreate(BaseModel):
    id: str
    field_path: str = Field(..., min_length=1, max_length=512)
    field_snippet: str | None = Field(default=None, max_length=400)
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"


class FieldAnnotationUpdate(BaseModel):
    comment: str | None = Field(default=None, min_length=1, max_length=4000)
    severity: Severity | None = None
    field_snippet: str | None = Field(default=None, max_length=400)
    resolved: bool | None = None


class CaseCommentCreate(BaseModel):
    id: str
    comment: str = Field(..., min_length=1, max_length=4000)
    severity: Severity = "note"


class CaseCommentUpdate(BaseModel):
    comment: str | None = Field(default=None, min_length=1, max_length=4000)
    severity: Severity | None = None


class StatusUpdate(BaseModel):
    status: ReviewStatus
    policy_verdict: PolicyReviewVerdict | None = None


class HeartbeatRequest(BaseModel):
    seconds: int = Field(..., ge=1, le=600)


class CaseReviewSummary(BaseModel):
    case_id: str
    status: ReviewStatus
    annotation_count: int
    comment_count: int
    severity_counts: dict[str, int]
    last_updated_at: datetime | None
    time_spent_seconds: int = 0
