"""Pydantic models for the per-reviewer tool review.

A *tool review* is one reviewer's structured assessment of the agent's
diagnostic tool catalog: free-form field annotations on the
tool↔pathology coverage (reusing :class:`FieldAnnotation`) plus any new
tools they want to propose. Unlike case reviews there is exactly one
tool-review file per (reviewer, dataset_version).

The catalog models (``ToolMeta`` / ``ConditionToolMapping`` /
``ToolCatalog``) are read-only; they describe the existing tool list
grouped by condition and are served by the catalog builder.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field

from .annotations import FieldAnnotation

# field_path conventions used by tool-review annotations:
#   "tool:<tool_name>"                                   — a tool in general
#   "tool:<tool_name>:param:<param_key>"                 — one parameter of a tool
#   "tool:<tool_name>:return:<field_name>"               — one return field of a tool
#   "condition:<condition_key>"                          — a condition's tool coverage
#   "condition_tool:<condition_key>:<tool>"              — one tool for one condition
#   "category:<category>"                                — a pathology category
# These are plain strings stored in FieldAnnotation.field_path; no new
# validation is needed beyond FieldAnnotation's own constraints.


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# --- Reviewer-authored proposals --------------------------------------


class ProposedTool(BaseModel):
    """A new diagnostic tool a reviewer thinks the agent should have."""

    id: str = Field(..., description="UUID, generated by client for optimistic UI")
    name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(..., min_length=1, max_length=4000)
    rationale: str = Field(
        default="",
        max_length=4000,
        description="Why this tool is needed / what gap it fills",
    )
    target_conditions: list[str] = Field(
        default_factory=list,
        description="Condition keys (enum values) this tool is relevant to",
    )
    modality: str | None = Field(
        default=None,
        max_length=120,
        description="Optional modality/category label for the proposed tool",
    )
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)


class ToolReview(BaseModel):
    """One reviewer's tool-review state for one dataset version."""

    reviewer_code: str
    dataset_version: str
    field_annotations: list[FieldAnnotation] = Field(
        default_factory=list, max_length=2000
    )
    proposed_tools: list[ProposedTool] = Field(default_factory=list, max_length=500)
    completed_at: datetime | None = Field(
        default=None,
        description="Set when the reviewer marks the tool review done; "
        "drives the first-run reminder.",
    )
    first_opened_at: datetime | None = None
    last_updated_at: datetime = Field(default_factory=_utcnow)


# --- Request payloads --------------------------------------------------


class ProposedToolCreate(BaseModel):
    id: str
    name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(..., min_length=1, max_length=4000)
    rationale: str = Field(default="", max_length=4000)
    target_conditions: list[str] = Field(default_factory=list)
    modality: str | None = Field(default=None, max_length=120)


class ProposedToolUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    description: str | None = Field(default=None, min_length=1, max_length=4000)
    rationale: str | None = Field(default=None, max_length=4000)
    target_conditions: list[str] | None = None
    modality: str | None = Field(default=None, max_length=120)


class ToolReviewCompleteUpdate(BaseModel):
    completed: bool = Field(
        ..., description="True to mark the tool review done, False to reopen it"
    )


# --- Read-only catalog models -----------------------------------------


class ToolParameter(BaseModel):
    """One parameter the agent passes when calling a tool."""

    name: str
    type: str  # JSON-Schema primitive: "string" | "integer" | "boolean" | "array" | "object"
    description: str = ""
    required: bool = False
    enum: list[str] | None = None
    default: str | int | bool | None = None
    items_type: str | None = None  # for arrays: the element type


class ToolOutputField(BaseModel):
    """One top-level field of a tool's returned Pydantic model."""

    name: str
    type: str  # human-readable: "str", "list[EEGFinding]", "dict[str, str]", ...
    description: str = ""
    required: bool = False


class ToolMeta(BaseModel):
    """Static description of one diagnostic tool, for display."""

    name: str
    label: str
    description: str
    modality: str | None = None
    cost_summary: str | None = None
    # I/O contract surfaced for tool-review annotations. Reviewers can flag a
    # specific parameter (`tool:<name>:param:<param>`) or return field
    # (`tool:<name>:return:<field>`) instead of only the tool as a whole.
    parameters: list[ToolParameter] = Field(default_factory=list)
    output_fields: list[ToolOutputField] = Field(default_factory=list)


GuidanceStatus = Literal["applied", "partial", "confirm", "no_change", "open", "retired"]


class ConditionToolGuidance(BaseModel):
    """One clinical reviewer's guidance for one tool in one condition, plus our answer.

    The July 2026 review rewrote tool descriptions *per condition*: "for MS, brain and cord
    MRI with an MS protocol", "not indicated in syncope". `ToolMeta.description` is a single
    string shown under every condition, so that text had nowhere to live — and it cannot go
    into the agent-facing `parameter_schema` either, because a condition-specific indication
    hands the agent the diagnosis it is meant to infer. This model is where it lives, served
    beside the condition→tool row and rendered in the review app only.
    """

    reviewer: int = Field(..., description="1 = chronic conditions, 2 = acute; never a code")
    guidance: str = Field(default="", description="The reviewer's own revised description")
    rationale: str = Field(default="", description="Their reasoning, including what they removed")
    source: str = Field(default="", description="The guideline they cite")
    requested_tier: str | None = Field(
        default=None, description="The tier they asked for in this condition"
    )
    status: GuidanceStatus = Field(..., description="What happened to this specific comment")
    our_response: str = Field(
        default="", description="What we did about it, including where we did not comply"
    )
    filed_under: list[str] = Field(
        default_factory=list,
        description="The row(s) they annotated, when the study belongs to a different tool: "
        "eleven comments describe studies the twelve-tool action space could not express",
    )


class ConditionToolMapping(BaseModel):
    """Which tools are required/optional for one condition."""

    condition: str = Field(..., description="Condition key (enum value)")
    label: str
    required_tools: list[str] = Field(default_factory=list)
    optional_tools: list[str] = Field(default_factory=list)
    guidance: dict[str, ConditionToolGuidance] = Field(
        default_factory=dict,
        description="Reviewer guidance for this condition, keyed by tool name. A tool may "
        "carry guidance without being in either tier list — that is a study the review asked "
        "for and no case orders yet, and hiding it would hide the gap.",
    )


class ToolCatalog(BaseModel):
    """The full read-only tool catalog for a dataset version."""

    version: str
    tools: list[ToolMeta] = Field(default_factory=list)
    universal_tools: list[str] = Field(
        default_factory=list,
        description="Tools available for every condition (e.g. literature, drug check)",
    )
    conditions: list[ConditionToolMapping] = Field(default_factory=list)
    unmapped_tools: list[str] = Field(
        default_factory=list,
        description="Tools in the catalog not referenced by any condition "
        "(a coverage gap reviewers may want to flag)",
    )


Severity = Literal["note", "issue", "error"]
