"""Pydantic models for the per-reviewer tool review.

A *tool review* is one reviewer's structured assessment of the agent's
diagnostic tool catalog: free-form field annotations on the
tool↔pathology coverage (reusing :class:`FieldAnnotation`) plus any new
tools they want to propose. Unlike case reviews there is exactly one
tool-review file per (reviewer, dataset_version).

The catalog models (``ToolMeta`` / ``ConditionToolMapping`` /
``ToolCatalog``) are read-only; they describe the existing tool list
grouped by condition and are served by the catalog builder.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field

from .annotations import FieldAnnotation

# field_path conventions used by tool-review annotations:
#   "tool:<tool_name>"                       — a tool in general
#   "condition:<condition_key>"              — a condition's tool coverage
#   "condition_tool:<condition_key>:<tool>"  — one tool for one condition
#   "category:<category>"                    — a pathology category
# These are plain strings stored in FieldAnnotation.field_path; no new
# validation is needed beyond FieldAnnotation's own constraints.


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# --- Reviewer-authored proposals --------------------------------------


class ProposedTool(BaseModel):
    """A new diagnostic tool a reviewer thinks the agent should have."""

    id: str = Field(..., description="UUID, generated by client for optimistic UI")
    name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(..., min_length=1, max_length=4000)
    rationale: str = Field(
        default="",
        max_length=4000,
        description="Why this tool is needed / what gap it fills",
    )
    target_conditions: list[str] = Field(
        default_factory=list,
        description="Condition keys (enum values) this tool is relevant to",
    )
    modality: str | None = Field(
        default=None,
        max_length=120,
        description="Optional modality/category label for the proposed tool",
    )
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)


class ToolReview(BaseModel):
    """One reviewer's tool-review state for one dataset version."""

    reviewer_code: str
    dataset_version: str
    field_annotations: list[FieldAnnotation] = Field(
        default_factory=list, max_length=2000
    )
    proposed_tools: list[ProposedTool] = Field(default_factory=list, max_length=500)
    completed_at: datetime | None = Field(
        default=None,
        description="Set when the reviewer marks the tool review done; "
        "drives the first-run reminder.",
    )
    first_opened_at: datetime | None = None
    last_updated_at: datetime = Field(default_factory=_utcnow)


# --- Request payloads --------------------------------------------------


class ProposedToolCreate(BaseModel):
    id: str
    name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(..., min_length=1, max_length=4000)
    rationale: str = Field(default="", max_length=4000)
    target_conditions: list[str] = Field(default_factory=list)
    modality: str | None = Field(default=None, max_length=120)


class ProposedToolUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=120)
    description: str | None = Field(default=None, min_length=1, max_length=4000)
    rationale: str | None = Field(default=None, max_length=4000)
    target_conditions: list[str] | None = None
    modality: str | None = Field(default=None, max_length=120)


class ToolReviewCompleteUpdate(BaseModel):
    completed: bool = Field(
        ..., description="True to mark the tool review done, False to reopen it"
    )


# --- Read-only catalog models -----------------------------------------


class ToolMeta(BaseModel):
    """Static description of one diagnostic tool, for display."""

    name: str
    label: str
    description: str
    modality: str | None = None
    cost_summary: str | None = None


class ConditionToolMapping(BaseModel):
    """Which tools are required/optional for one condition."""

    condition: str = Field(..., description="Condition key (enum value)")
    label: str
    required_tools: list[str] = Field(default_factory=list)
    optional_tools: list[str] = Field(default_factory=list)


class ToolCatalog(BaseModel):
    """The full read-only tool catalog for a dataset version."""

    version: str
    tools: list[ToolMeta] = Field(default_factory=list)
    universal_tools: list[str] = Field(
        default_factory=list,
        description="Tools available for every condition (e.g. literature, drug check)",
    )
    conditions: list[ConditionToolMapping] = Field(default_factory=list)
    unmapped_tools: list[str] = Field(
        default_factory=list,
        description="Tools in the catalog not referenced by any condition "
        "(a coverage gap reviewers may want to flag)",
    )


Severity = Literal["note", "issue", "error"]
