"""FastAPI application for the NeuroAgent web dashboard."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from neuroagent_schemas import NeuroBenchCase

from .routes import cases, hospitals, agent, models, traces, copilot

logger = logging.getLogger(__name__)

# Paths relative to agent-platform/
DATA_ROOT = Path(__file__).resolve().parents[4] / "data"
RULES_DIR = Path(__file__).resolve().parents[3] / "config" / "hospital_rules"
TRACES_DIR = DATA_ROOT / "traces"
WEB_DIST = Path(__file__).resolve().parents[4] / "web" / "dist"

DATASETS = {
    "v1": {
        "path": DATA_ROOT / "neurobench_v1",
        "name": "NeuroBench v1",
        "description": "100 synthetic cases generated by Claude",
    },
    "v2": {
        "path": DATA_ROOT / "neurobench_v2",
        "name": "NeuroBench v2",
        "description": "100 cases seeded from real PMC case reports",
    },
}


def _load_dataset(dataset_path: Path) -> tuple[dict[str, dict[str, Any]], dict[str, NeuroBenchCase]]:
    """Load all cases from a dataset directory, returning (case_index, case_objects)."""
    case_index: dict[str, dict[str, Any]] = {}
    case_objects: dict[str, NeuroBenchCase] = {}

    cases_dir = dataset_path / "cases"
    if cases_dir.exists():
        for case_file in sorted(cases_dir.glob("*.json")):
            try:
                data = json.loads(case_file.read_text())
                case = NeuroBenchCase.model_validate(data)
                case_objects[case.case_id] = case
                case_index[case.case_id] = {
                    "case_id": case.case_id,
                    "condition": case.condition.value,
                    "difficulty": case.difficulty.value,
                    "encounter_type": case.encounter_type.value,
                    "age": case.patient.demographics.age,
                    "sex": case.patient.demographics.sex,
                    "chief_complaint": case.patient.chief_complaint,
                }
            except Exception as e:
                logger.error("Failed to load case %s: %s", case_file.name, e)

    return case_index, case_objects


def create_app() -> FastAPI:
    app = FastAPI(title="NeuroAgent Dashboard API", version="1.0.0")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Pre-load all datasets
    all_datasets: dict[str, tuple[dict[str, dict[str, Any]], dict[str, NeuroBenchCase]]] = {}
    for version, info in DATASETS.items():
        idx, objs = _load_dataset(info["path"])
        all_datasets[version] = (idx, objs)
        logger.info("Loaded %d cases from %s", len(idx), version)

    # Default to v1
    default_version = "v1"
    app.state.active_dataset = default_version
    app.state.all_datasets = all_datasets
    app.state.case_index = all_datasets[default_version][0]
    app.state.case_objects = all_datasets[default_version][1]

    # Ensure traces directory exists
    TRACES_DIR.mkdir(parents=True, exist_ok=True)

    # Store shared state on app
    app.state.rules_dir = str(RULES_DIR)
    app.state.traces_dir = TRACES_DIR
    app.state.dataset_path = DATASETS[default_version]["path"]

    # Register routes
    app.include_router(cases.router, prefix="/api/v1")
    app.include_router(hospitals.router, prefix="/api/v1")
    app.include_router(models.router, prefix="/api/v1")
    app.include_router(agent.router, prefix="/api/v1")
    app.include_router(traces.router, prefix="/api/v1")
    app.include_router(copilot.router, prefix="/api/v1")

    # Serve frontend static files in production
    if WEB_DIST.exists():
        app.mount("/", StaticFiles(directory=str(WEB_DIST), html=True), name="static")

    return app


app = create_app()
