#!/bin/bash
# End-to-end fine-tuning comparison for NeuroAgent: SFT a model on the gold
# trajectories (v5 train split), then evaluate base vs SFT on the held-out test split.
#
# Run: bash agent-platform/scripts/training/run_finetuning_comparison.sh [model_tag]
#   model_tag defaults to Qwen3.5-9B; pass Qwen3.5-4B for the small student.
#
# This is a thin orchestrator over the maintained launchers (each is idempotent, so
# re-running after an interruption is safe):
#   run_sft_training.sh     — QLoRA/bf16-LoRA SFT on the train split, adapter to EOS
#   run_definitive_eval.sh  — greedy + sampled base-vs-SFT eval with paired stats
# For preference/RL stages see run_dpo_training.sh and run_rft.sh.
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"  # repo root

MODEL_TAG="${1:-Qwen3.5-9B}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPLITS="data/neurobench/splits"
DATA="${DATA:-training_data/gold_trajectories/trajectories.jsonl}"

# === Preconditions =======================================================
# v5 train/test split (500/100 cases, checked into git). Regenerate only
# deliberately — it would invalidate every existing run:
#   uv run python -m neuroagent.training.data.make_train_test_split
for f in train_cases.txt test_cases.txt split_manifest.json; do
    if [ ! -f "$SPLITS/$f" ]; then
        echo "ERROR: missing $SPLITS/$f — regenerate with:" >&2
        echo "  uv run python -m neuroagent.training.data.make_train_test_split" >&2
        exit 1
    fi
done

# Gold trajectories (generated by Claude subagents; see
# generate_gold_trajectories.py --prepare-prompts and batch_generate_trajectories.py).
if [ ! -f "$DATA" ]; then
    echo "ERROR: no gold trajectories at $DATA" >&2
    echo "Generate them first (prepare prompts, then run the trajectory subagents):" >&2
    echo "  uv run python -m neuroagent.training.data.generate_gold_trajectories \\" >&2
    echo "      --dataset data/neurobench --output training_data/gold_trajectories --prepare-prompts" >&2
    exit 1
fi

echo "========================================="
echo " NeuroAgent Fine-Tuning Comparison"
echo " Model:  Qwen/$MODEL_TAG"
echo " Data:   $DATA ($(wc -l < "$DATA") trajectories)"
echo " Splits: $SPLITS ($(wc -l < "$SPLITS/train_cases.txt") train / $(wc -l < "$SPLITS/test_cases.txt") test)"
echo "========================================="

# === Phase 1: SFT (train split only; 10% val carve-out; adapter lands on EOS) ===
echo ""
echo "[Phase 1] SFT training..."
DATA="$DATA" SPLITS="$SPLITS" bash "$SCRIPT_DIR/run_sft_training.sh" "Qwen/$MODEL_TAG"

# === Phase 2: base-vs-SFT evaluation on the held-out test split ===
# Greedy pass@1 + sampled reliability + judge bundles + paired significance.
echo ""
echo "[Phase 2] Base-vs-SFT evaluation..."
bash "$SCRIPT_DIR/run_definitive_eval.sh" "$MODEL_TAG"

echo ""
echo "========================================="
echo " Pipeline complete."
echo " Results: results/definitive_eval/$MODEL_TAG/"
echo " Judge bundles there feed prepare_judge_batches.py -> llm-judge -> aggregate_judge_scores.py"
echo "========================================="
