"""Token-exact multi-turn ReAct rollout for GRPO.

The single-turn GRPO rollout never showed the policy a tool *response*, so the reward was
computed on a one-shot completion and did not transfer to the multi-turn agent. This drives
the REAL ReAct loop — the model writes a turn, we execute its tool calls against the
deterministic ``MockServer`` for the case, feed the results back, and let it continue — and
returns the full token stream with a mask that is 1 on the model's own tokens and 0 on the
tool-result/reflection tokens it merely conditioned on. GRPO then updates only on the tokens
the policy actually produced (the tool tokens must not receive gradient), and the reward is
scored on the genuine :class:`AgentTrace`.

Token alignment follows TRL's own tool loop: the sequence is built by CONCATENATING token
ids (never re-tokenising the whole conversation, which would drift token boundaries across
message seams), and the tokens the chat template inserts for a tool result + the next
generation prompt are recovered as the delta of a minimal dummy render (``_tool_suffix_ids``).

The policy is injected as ``generate_fn`` so the whole loop is unit-testable on CPU with the
real tokenizer and a canned policy — only the actual model forward needs a GPU.
"""

from __future__ import annotations

import contextlib
import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Callable, Protocol

from ..rewards.online_reward import extract_tool_calls

if TYPE_CHECKING:
    from neuroagent_schemas import NeuroBenchCase

    from ...agent.reasoning import AgentTrace

logger = logging.getLogger(__name__)

# generate_fn: given the current full prompt token ids for ONE trajectory, return the token
# ids the policy generates for the next assistant turn (including the terminating EOS token).
GenerateFn = Callable[[list[int]], list[int]]


class _Tokenizer(Protocol):
    def apply_chat_template(self, conversation: list[dict], **kwargs: Any) -> Any: ...
    def __call__(self, text: str, **kwargs: Any) -> Any: ...
    def decode(self, ids: list[int], **kwargs: Any) -> str: ...


@dataclass
class RolloutResult:
    """One completed trajectory, ready for GRPO."""

    case_id: str
    prompt_ids: list[int]
    completion_ids: list[int]
    # env_mask[i] == 1 iff completion_ids[i] was generated by the policy (gets gradient);
    # 0 for tool-result and reflection/generation-prompt tokens.
    env_mask: list[int]
    logprobs: list[float]
    messages: list[dict[str, Any]]
    num_turns: int
    num_tool_calls: int
    truncated: bool
    # Assistant turns cut off by the PER-TURN generation cap (no EOS emitted). Distinct from
    # `truncated`, which is the whole-completion budget. A clipped turn that carries no tool
    # call is indistinguishable from a deliberate conclusion further down, so it is counted
    # here and surfaced by the caller rather than left silent.
    clipped_turns: int
    # True when the budget reserve cut the workup short and the agent was told to conclude.
    # NOT truncation — the trajectory ends properly with a diagnosis, which is the point of the
    # reserve — but the workup is shallower than the policy would have chosen. Without this the
    # rollout reports "truncated 0%" while curtailing half the workups (measured: MAX_COMPLETION
    # 4096 fits only 50.9% of the SFT policy's real workups end to end).
    forced_conclusion: bool
    trace: AgentTrace

    def __post_init__(self) -> None:
        if self.logprobs and len(self.logprobs) != len(self.completion_ids):
            raise ValueError(
                f"logprobs ({len(self.logprobs)}) must align with completion_ids "
                f"({len(self.completion_ids)})"
            )
        if len(self.completion_ids) != len(self.env_mask):
            raise ValueError(
                f"completion_ids ({len(self.completion_ids)}) and env_mask "
                f"({len(self.env_mask)}) must be the same length"
            )


@dataclass
class _TrajState:
    """Mutable in-flight state for one trajectory while the batch advances turn by turn."""

    case: Any
    messages: list[dict[str, Any]]
    prompt_ids: list[int]
    mock_server: Any
    cost_tracker: Any
    completion_ids: list[int] = field(default_factory=list)
    env_mask: list[int] = field(default_factory=list)
    # Sampling logprob per completion token, 0.0 on tokens the policy did not generate.
    logprobs: list[float] = field(default_factory=list)
    turns: list = field(default_factory=list)
    tools_called: list[str] = field(default_factory=list)
    final_response: str = ""
    num_tool_calls: int = 0
    turn_number: int = 0
    truncated: bool = False
    clipped_turns: int = 0
    done: bool = False
    must_conclude: bool = False

    def trace_or(self, trace):
        return trace


@dataclass
class ReactRollout:
    """Drive the ReAct loop for one case and emit a token-exact, masked trajectory.

    Args:
        tokenizer: the model tokenizer (chat template + tool schemas).
        tools: the JSON tool schemas the orchestrator sends at inference.
        system_prompt: the composed system prompt (base + reasoning style + hospital rules).
        max_turns: assistant-turn cap (the orchestrator uses 15).
        max_completion_tokens: total generated+tool budget for the completion; the loop stops
            once the concatenated completion reaches it.
        enable_reflection: append the reflection user message after tool results, exactly as
            the orchestrator does when ``enable_reflection`` is set.
        reflection_message: the reflection message dict (role/content), or None.
    """

    tokenizer: _Tokenizer
    tools: list[dict[str, Any]]
    system_prompt: str
    max_turns: int = 15
    max_completion_tokens: int = 4096
    # Tokens held back so the agent can always state its assessment. Without this, hitting the
    # budget ENDS the rollout mid-workup: the trajectory never reaches a diagnosis, correctness
    # (the largest reward weight) is structurally 0, and the group advantage ends up rewarding
    # "finished within budget" over "diagnosed correctly" — i.e. it teaches the model to order
    # FEWER tests. Measured: an identical trajectory scored composite 0.664 with the diagnosis
    # and 0.296 without it. When the remaining budget drops below this, tool calls stop being
    # executed and the agent is asked to conclude.
    final_answer_reserve: int = 640
    # Reflection is injected as a USER message. Under Qwen3.5's SHIPPED (inference) template
    # that is fatal: it strips <think> from any assistant turn a user message follows, which
    # mutates history and breaks the append-only concatenation this rollout depends on
    # (measured: append-only=False, reasoning dropped). TRL's qwen3_5 TRAINING template keeps
    # the reasoning and stays append-only through tool + reflection turns (measured: both True),
    # so with `chat_template` set to it, reflection is safe and matches serving.
    enable_reflection: bool = True
    reflection_message: dict[str, str] | None = None
    # Asked of the agent when the budget reserve is reached, so it concludes instead of being
    # cut off mid-workup. Masked like any other environment message.
    conclude_message: dict[str, str] | None = field(default_factory=lambda: {
        "role": "user",
        "content": (
            "You have no further diagnostic budget. Do not order any more tests. "
            "State your final assessment now, using the required sections: "
            "### Primary Diagnosis, ### Differential Diagnoses, ### Recommendations."
        ),
    })
    # Chat template used for ALL rendering. Must be the think-preserving TRAINING template;
    # the eval server has to be given the SAME template or train/serve diverge again.
    chat_template: str | None = None
    # Cache the dummy prefix ids (depends only on tokenizer+tools) across trajectories.
    _dummy_prefix_ids: list[int] | None = field(default=None, repr=False)

    @property
    def _eos_ids(self) -> frozenset[int]:
        """Ids that legitimately END an assistant turn.

        Both matter for Qwen3.5: `eos_token_id` is `<|im_end|>`, but generation may also stop
        on `<|endoftext|>`, and the tokenizer's `eos_token_id` alone would misread that as a
        clipped turn. Anything else at the tail means the per-turn cap cut the turn short.
        """
        ids = {getattr(self.tokenizer, "eos_token_id", None)}
        for tok in ("<|im_end|>", "<|endoftext|>"):
            with contextlib.suppress(Exception):
                ids.add(self.tokenizer.convert_tokens_to_ids(tok))
        return frozenset(i for i in ids if isinstance(i, int) and i >= 0)

    # -- token helpers ------------------------------------------------------

    def _render_ids(self, messages: list[dict], add_generation_prompt: bool) -> list[int]:
        """Token ids straight from the chat template.

        Tokenising the template directly (not re-encoding its text) is essential: a
        text round-trip can merge tokens across the message seam, which breaks the
        prefix invariant the suffix delta relies on.
        """
        kwargs: dict[str, Any] = {}
        if self.chat_template is not None:
            kwargs["chat_template"] = self.chat_template
        ids = self.tokenizer.apply_chat_template(
            messages,
            tools=self.tools,
            add_generation_prompt=add_generation_prompt,
            tokenize=True,
            return_dict=False,
            **kwargs,
        )
        # A single (non-batched) conversation returns a flat list of ids.
        return list(ids)

    def _prompt_ids(self, messages: list[dict]) -> list[int]:
        return self._render_ids(messages, add_generation_prompt=True)

    def _tool_suffix_ids(self, tool_messages: list[dict]) -> list[int]:
        """Tokens the template inserts for ``tool_messages`` + the next generation prompt.

        Recovered as the delta of a minimal dummy conversation so it is independent of the
        (arbitrarily long) real history and never re-tokenises it. Mirrors TRL's
        ``_get_tool_suffix_ids``; raises if the prefix is not actually a prefix (which would
        mean the template is context-sensitive and the concatenation would be misaligned).
        """
        # The dummy assistant must look like a REAL turn — reasoning inside <think> in
        # `content`, and a dict-argument tool call — or Qwen3.5's template renders it
        # differently once it is no longer the final message (it only leaves a content-embedded
        # think intact), and the prefix invariant breaks. The tool-message + generation-prompt
        # tokens are context-independent, so this dummy yields the correct suffix for any turn.
        dummy = [
            {"role": "user", "content": "dummy"},
            {
                "role": "assistant",
                "content": "<think>\ndummy\n</think>\n\ndummy",
                "tool_calls": [
                    {
                        "id": "call_1",
                        "type": "function",
                        "function": {"name": "analyze_brain_mri", "arguments": {"x": "y"}},
                    }
                ],
            },
        ]
        if self._dummy_prefix_ids is None:
            prefix_ids = self._render_ids(dummy, add_generation_prompt=False)
            # The template closes the assistant turn with `<|im_end|>\n`. A real generated turn
            # ends at `<|im_end|>` (no trailing newline), so strip trailing whitespace tokens
            # from the prefix — the delta then reclaims that `\n`, and the concatenation reads
            # `…<|im_end|>\n<|im_start|>…` exactly as the template would render it.
            while prefix_ids and not self.tokenizer.decode([prefix_ids[-1]]).strip():
                prefix_ids = prefix_ids[:-1]
            self._dummy_prefix_ids = prefix_ids
        prefix = self._dummy_prefix_ids
        full = self._render_ids(dummy + tool_messages, add_generation_prompt=True)
        if full[: len(prefix)] != prefix:
            raise ValueError(
                "Tool-suffix delta is misaligned: the dummy prefix is not a prefix of the "
                "full render. The chat template appears context-sensitive; token "
                "concatenation cannot be trusted for masking."
            )
        return full[len(prefix) :]

    # -- the loop -----------------------------------------------------------

    def _new_state(self, case: NeuroBenchCase, patient_info: str,
                   mock_server: Any, cost_tracker: Any) -> _TrajState:
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": patient_info},
        ]
        return _TrajState(
            case=case,
            messages=messages,
            prompt_ids=self._prompt_ids(messages),
            mock_server=mock_server,
            cost_tracker=cost_tracker,
        )

    def _advance(self, st: _TrajState, gen_ids: list[int],
                 gen_logprobs: list[float] | None = None) -> None:
        """Fold one generated assistant turn into a trajectory, executing its tool calls.

        Sets ``st.done`` when the trajectory concludes (no tool calls) or runs out of budget.
        This is the per-trajectory half of the loop; ``rollout_batch`` drives the generation.
        """
        from ...agent.reasoning import AgentTurn
        from ...llm.prompts import format_tool_result

        if not gen_ids:
            st.done = True
            return

        # The policy's own tokens — these get gradient.
        st.completion_ids.extend(gen_ids)
        st.env_mask.extend([1] * len(gen_ids))
        # Sampling logprobs, when the backend supplies them (vLLM does; HF generate does not).
        # TRL needs these for the vLLM importance-sampling correction, because the engine's
        # sampling distribution is not identical to the training model's.
        if gen_logprobs is not None:
            lp = list(gen_logprobs[: len(gen_ids)])
            lp += [0.0] * (len(gen_ids) - len(lp))
            st.logprobs.extend(lp)
        else:
            st.logprobs.extend([0.0] * len(gen_ids))
        st.turn_number += 1

        # A turn that stops without EOS was cut by the per-turn `max_new_tokens` cap, not by
        # the model deciding it was finished. That distinction is invisible downstream: a
        # clipped turn usually carries no parseable tool call, so the branch below reads it as
        # a deliberate conclusion and the trajectory is scored as if the agent chose to stop
        # without ordering any tests. Count it so a cap that is too tight shows up as a number
        # instead of as inexplicably bad rewards.
        if gen_ids[-1] not in self._eos_ids:
            st.clipped_turns += 1

        text = self.tokenizer.decode(gen_ids, skip_special_tokens=True)
        calls = extract_tool_calls(text)
        content = _assistant_content(text)

        if calls and st.must_conclude:
            # Forced conclusion: the budget no longer allows another tool round-trip, so any
            # tool call here is dropped and the turn is read as the final assessment.
            logger.debug("Budget reserve reached — treating turn as final for %s",
                         st.case.case_id)
            calls = []

        if not calls:
            # Concluding turn: no tool calls → the agent is done.
            st.turns.append(AgentTurn(turn_number=st.turn_number, role="assistant",
                                      content=content, tool_calls=None))
            st.final_response = _extract_assessment_safe(text)
            st.done = True
            return

        # Record the assistant turn and mirror it into the message list so the next
        # render conditions on it (as text tokens already in completion_ids).
        st.turns.append(AgentTurn(
            turn_number=st.turn_number, role="assistant", content=content,
            tool_calls=[{"function": {"name": c["tool_name"], "arguments": c["parameters"]}}
                        for c in calls],
        ))
        st.messages.append(_assistant_message(text, calls))

        # Execute each call against the deterministic mock server, in order.
        tool_messages: list[dict[str, Any]] = []
        for c in calls:
            st.num_tool_calls += 1
            st.tools_called.append(c["tool_name"])
            result = st.mock_server.get_output(c["tool_name"], c["parameters"])
            cost_entry = st.cost_tracker.compute_cost(c["tool_name"], c["parameters"])
            result.cost_usd = cost_entry.cost_usd
            st.turn_number += 1
            st.turns.append(AgentTurn(turn_number=st.turn_number, role="tool",
                                      content=None, tool_results=[result.model_dump()]))
            tool_messages.append(format_tool_result(
                tool_call_id=f"call_{st.num_tool_calls}",
                tool_name=c["tool_name"],
                result=result.model_dump(),
            ))
        if self.enable_reflection and self.reflection_message is not None:
            tool_messages.append(dict(self.reflection_message))
        st.messages.extend(tool_messages)

        # The tool-result + reflection + next-generation-prompt tokens: conditioned on,
        # not generated → mask 0.
        suffix_ids = self._tool_suffix_ids(tool_messages)

        # Decide BEFORE appending. A single tool report can be larger than the whole reserve
        # (NeuroBench reports run ~600-1000 tokens), so checking afterwards lets one result
        # jump straight past the reserve window and truncate the trajectory — which then never
        # reaches a diagnosis. If this result would not leave room to conclude, drop it and ask
        # for the assessment instead. The calls themselves stay on the trace: the agent did
        # order them, and they are what `tools_called` and cost are scored on.
        if len(st.completion_ids) + len(suffix_ids) + self.final_answer_reserve > self.max_completion_tokens:
            logger.debug(
                "Tool result would exhaust the budget for %s — concluding instead",
                st.case.case_id,
            )
            self._request_conclusion(st)
            return

        st.completion_ids.extend(suffix_ids)
        st.env_mask.extend([0] * len(suffix_ids))
        st.logprobs.extend([0.0] * len(suffix_ids))  # not generated by the policy

        remaining = self.max_completion_tokens - len(st.completion_ids)
        if remaining <= 0:
            # No room even to conclude — a genuinely truncated trajectory.
            st.truncated = True
            st.completion_ids = st.completion_ids[: self.max_completion_tokens]
            st.env_mask = st.env_mask[: self.max_completion_tokens]
            st.logprobs = st.logprobs[: self.max_completion_tokens]
            st.done = True
        elif remaining <= self.final_answer_reserve:
            self._request_conclusion(st)

    def _request_conclusion(self, st: _TrajState) -> None:
        """Ask the agent to state its assessment now, because the budget is nearly spent.

        Marks the trajectory so any further tool calls are ignored, and appends the request as
        a masked environment message. This is what keeps a budget-limited trajectory scoreable:
        it still ends with a diagnosis, so `correctness` — the largest reward component — is
        earnable rather than structurally zero.
        """
        st.must_conclude = True
        if self.conclude_message is None:
            return
        conclude = [dict(self.conclude_message)]
        st.messages.extend(conclude)
        suffix = self._tool_suffix_ids(conclude)
        room = self.max_completion_tokens - len(st.completion_ids)
        suffix = suffix[:room] if room > 0 else []
        st.completion_ids.extend(suffix)
        st.env_mask.extend([0] * len(suffix))
        st.logprobs.extend([0.0] * len(suffix))

    def _finish(self, st: _TrajState) -> RolloutResult:
        from ...agent.reasoning import AgentTrace

        trace = AgentTrace(
            case_id=st.case.case_id,
            turns=st.turns,
            messages=st.messages,
            final_response=st.final_response,
            total_tool_calls=st.num_tool_calls,
            tools_called=st.tools_called,
            total_cost_usd=st.cost_tracker.total_cost_usd,
            cost_entries=[e.model_dump() for e in st.cost_tracker.entries],
        )
        return RolloutResult(
            case_id=st.case.case_id,
            prompt_ids=st.prompt_ids,
            completion_ids=st.completion_ids,
            env_mask=st.env_mask,
            logprobs=st.logprobs,
            messages=st.messages,
            num_turns=st.turn_number,
            num_tool_calls=st.num_tool_calls,
            truncated=st.truncated,
            clipped_turns=st.clipped_turns,
            forced_conclusion=st.must_conclude,
            trace=st.trace_or(trace),
        )

    def rollout_batch(
        self,
        items: list[tuple[NeuroBenchCase, str, Any, Any]],
        generate_batch_fn: Callable[[list[list[int]]], list[list[int]]],
    ) -> list[RolloutResult]:
        """Run MANY trajectories, advancing them a turn at a time in lockstep.

        All still-active trajectories have their turn-k generation issued as ONE batched
        call. Generating them one at a time instead costs a full ~6k-token prefill per
        trajectory per turn — measured at ~5 min/step for only 4 trajectories, i.e. ~21h for
        a 250-step run. Batching amortises that across the group, which is the difference
        between a tractable run and an intractable one.

        ``items`` is (case, patient_info, mock_server, cost_tracker) per trajectory; each
        needs its OWN mock_server/cost_tracker so trajectories stay isolated.
        """
        states = [self._new_state(c, p, ms, ct) for c, p, ms, ct in items]
        active = list(range(len(states)))

        for _ in range(self.max_turns):
            if not active:
                break
            batch_ids = [states[i].prompt_ids + states[i].completion_ids for i in active]
            gens = generate_batch_fn(batch_ids)
            # The generator may return ids only, or (ids, logprobs) per row.
            still_active: list[int] = []
            for idx, gen in zip(active, gens):
                if isinstance(gen, tuple):
                    gen_ids, gen_lp = gen
                else:
                    gen_ids, gen_lp = gen, None
                self._advance(states[idx], list(gen_ids), gen_lp)
                if not states[idx].done:
                    still_active.append(idx)
            active = still_active
        for i in active:  # hit max_turns without concluding
            states[i].truncated = True

        return [self._finish(st) for st in states]

    def rollout_one(
        self,
        case: NeuroBenchCase,
        patient_info: str,
        generate_fn: GenerateFn,
        mock_server: Any,
        cost_tracker: Any,
    ) -> RolloutResult:
        """Single-trajectory convenience wrapper over :meth:`rollout_batch`."""
        return self.rollout_batch(
            [(case, patient_info, mock_server, cost_tracker)],
            lambda batch: [generate_fn(batch[0])],
        )[0]


# ---------------------------------------------------------------------------
# text helpers — kept in sync with the orchestrator's own formatting
# ---------------------------------------------------------------------------

def _assistant_content(text: str) -> str | None:
    """The assistant's committed narrative (tool-call blocks removed), or None if empty."""
    import re
    stripped = re.sub(r"<tool_call>.*?</tool_call>", "", text, flags=re.DOTALL).strip()
    return stripped or None


def _assistant_message(text: str, calls: list[dict]) -> dict[str, Any]:
    """An OpenAI-style assistant message mirroring the generated turn.

    Content is the full generated text (its own token ids are already in the completion
    stream); tool_calls carry the parsed calls so the chat template renders the tool
    plumbing for the suffix delta. This exists only to feed ``_tool_suffix_ids`` a
    well-formed conversation — the token ids come from generation, not from re-rendering it.
    """
    msg: dict[str, Any] = {"role": "assistant", "content": text}
    if calls:
        # Arguments as a DICT, not a JSON string: Qwen3.5's chat template indexes them as a
        # mapping and raises on a string. (The OpenAI wire format uses a JSON string; that
        # conversion belongs at the serving boundary, not here.)
        msg["tool_calls"] = [
            {
                "id": f"call_{i + 1}",
                "type": "function",
                "function": {"name": c["tool_name"], "arguments": c["parameters"]},
            }
            for i, c in enumerate(calls)
        ]
    return msg


def _extract_assessment_safe(text: str) -> str:
    """The committed assessment, via the orchestrator's extractor (think-stripped section)."""
    from ...agent.orchestrator import _extract_assessment

    # Drop the leading (prompt-opened) think, matching the serving split, then extract.
    body = text.split("</think>", 1)[1] if "</think>" in text else text
    return _extract_assessment(body.strip())
